apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-singlepod
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ozgurozturknet/k8s:green
        ports:
        - containerPort: 8080
